<div class="col-md-8 offset-2">
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label for="from"><strong>From: </strong></label>
                <label for="from">{{ $sender }}</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="title"><strong>Title: </strong></label>
                <label for="from">{{ $title }}</label>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="body"><strong>Body: </strong></label>
                <label for="from">{{ $body }}</label>
            </div>
        </div>
    </div>
</div>
<br>
<small>Do not reply. This is an autogenerated email.</small>
